### ISSUE TITLE
Improve require time by using useAutoload: true

### ISSUE THREAD

**Issue by technicalpickles** [DataDog/datadog-api-client-ruby#1061]
**Note:**
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked.

**Is your feature request related to a problem? Please describe.**
This library has a lot of ruby files required. This takes time even if the library isn't used. This adds up when you have multiple libraries that use OpenAPI. In our application, this takes 0.3s on an M1 at Rails boottime.

**Describe the solution you'd like**

OpenAPI added an option `useAutoload` which switches to autoload. That way, files are only required when they use access a client. 

**Describe alternatives you've considered**
I tried manually changing this previously before realizing this was auto-generated https://github.com/DataDog/datadog-api-client-ruby/pull/537

**Additional context**

https://github.com/OpenAPITools/openapi-generator/issues/12648
https://github.com/OpenAPITools/openapi-generator/pull/13153

**Comment by skarimo** [comment]
👋 We recently introduced autoloading with the zeitwerk library in the V2 version of the client. See https://github.com/DataDog/datadog-api-client-ruby/pull/989

**Comment by technicalpickles** [comment]
That's great! Is there something similar in V1 already? We have some usage of it still.

**Comment by therve** [comment]
This is the v2 of the client, but it contains both the v1 and v2 versions of our API.
