### ISSUE TITLE
backwards-incompatible change in 2.10

### ISSUE THREAD

**Issue by michaelglass** [DataDog/datadog-api-client-ruby#1336]
**Describe the bug**
I wouldn't call this a bug, but rather an unintended backwards-incompatibility breakage in version 2.10

This is more of an FYI than a real issue. <3

[I guess the source was this line](https://github.com/DataDog/datadog-api-client-ruby/blame/14c998573d5ffb3587bcded5426add4d5be2f31a/lib/datadog_api_client/v2/models/logs_aggregate_bucket_value.rb#L49).

In 2.9 and previous, we would consistently have to call `.data` to fetch Floats / Ints out of `LogsAggregateBucketValue`. As of 2.10, Floats don't require `.data` but `Integers` still do. 

I _believe_ some data is returned from the API as Integer which makes parsing the results trickier than previously

**To Reproduce**
Write code to fetches both Float data out of `LogsAggregateBucketValue` that works with 2.9. Upgrade to 2.10

**Expected behavior**
The code continues to work

**Environment and Versions (please complete the following information):**
- version for this project in use.
2.10.0
- services, libraries, languages and tools list and versions.
n/a

**Comment by michaelglass** [comment]
closing this until I can confirm we're actually getting integer data back from the API call (or is this a nonsequitur related to our test API recordings). In any case calling `.data` for Float data is a compatibility regression (although probably a nicer API!)"

**Comment by therve** [comment]
Thanks for the report! I think that's a long present bug highlight by the change you mentioned, but the behavior should be fixed by #1340 .

**Comment by therve** [comment]
I'll close it when it's merged.
