### ISSUE TITLE
Please add pagination support to get_team_membership

### ISSUE THREAD

**Issue by seveas** [DataDog/datadog-api-client-ruby#1710]
**Note:**
If you have a feature request, you should [contact support](https://docs.datadoghq.com/help/) so the request can be properly tracked.

**Is your feature request related to a problem? Please describe.**
We have teams of more than 100 people, so we'd love to see `get_team_memberships` get a `get_team_memberships_with_pagination` sibling for easy querying.

**Describe the solution you'd like**
I tried adding an `x-pagination` section to the relevant section in openapi.yaml, but was unable to run the generator.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by skarimo** [comment]
Thanks for opening the issue. This is resolved by https://github.com/DataDog/datadog-api-client-ruby/pull/1712 and will be available in the next release

**Comment by seveas** [comment]
Thanks, that was fast!
