### ISSUE TITLE
Autoloading issue with class in new version 2.26.0

### ISSUE THREAD

**Issue by aditya-cherukuri** [DataDog/datadog-api-client-ruby#1991]
**Describe the bug**
The filename of a class in the version 2.26.0 is causing an autoloading name error. The file is question is:
`datadog_api_client/v2/models/entity_v3_api_version.rb`

I understand this file might have been autogenerated but it leads to an exception when used with the Zeitwerk autoloader

**To Reproduce**
Install the gem and use a spec file that looks like this on a rails installation. 
```
describe "Zeitwerk" do
  it "eager loads all files" do
    expect { Zeitwerk::Loader.eager_load_all }.not_to raise_error
  end
end
```

**Expected behavior**
No Exception on autoload.

**Screenshots**
```
expected no Exception, got #<Zeitwerk::NameError: expected file ../.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/dat...ls/entity_v3_api_version.rb to define constant DatadogAPIClient::V2::EntityV3ApiVersion, but didn't> with backtrace:
```

**Environment and Versions (please complete the following information):**
I'm currently using rails version 7.1.3.4 with ruby version 3.2.3 
datadog_api_client_ruby version 2.26.0

**Additional context**
I believe this problem can be fixed if the file is renamed to `entity_v3_a_p_i_version.rb` if you intend to keep the same class name otherwise the class has to be renamed to `EntityV3ApiVersion` and all references would have to be updated

**Comment by skarimo** [comment]
Hello, thanks for the report. We have released `v2.26.1` which includes a fix for loading the models.
