### ISSUE TITLE
Model equality check is broken in many models

### ISSUE THREAD

**Issue by benortiz** [DataDog/datadog-api-client-ruby#2140]
**Description**

Across many models with "additionalAttributes", the equality check effectively only checks if additionalAttributes is equal. See lines 273 and 274 below.

https://github.com/DataDog/datadog-api-client-ruby/blob/130eb02527f192df868e928d6cfeea53b3acb05e/lib/datadog_api_client/v2/models/service_definition_v2_dot2.rb#L256-L275

Since this is so widespread, it seems like an issue with code generation. When regenerated with the fix to this issue, the individual code might change like so:

```diff
           tier == o.tier &&
-          type == o.type
+          type == o.type &&
           additional_properties == o.additional_properties
```

**To Reproduce**

Initialize any two different models that can have additionalAttributes and run an equality comparison:

```ruby
> DatadogAPIClient::V2::ServiceDefinitionV2Dot2.new == DatadogAPIClient::V2::ServiceDefinitionV1.new
=> true
```

Or initialize the same model but with different properties and run an equality comparison:
```ruby
> DatadogAPIClient::V2::ServiceDefinitionV2Dot2.new(dd_service: "serviceA") == DatadogAPIClient::V2::ServiceDefinitionV2Dot2.new(dd_service: "serviceB")
=> true
```

**Expected behavior**

1. No two objects of different classes ought to be equivalent.
2. When comparing instances of the same classes with different model property values, they should not be equivalent. 

**Environment and Versions:**
A clear and precise description of your setup:

- Ruby 3.2.6
- DatadogAPIClient 2.28.1
- Also present in `master`.

**Comment by nkzou** [comment]
Hey there, thanks for reporting this - we've patched the code generator and a new release will be made sometime next week that includes this bugfix. Thanks again!
