### ISSUE TITLE
Unable to configure client - 1.0.0.beta.2

### ISSUE THREAD

**Issue by mariogintili** [DataDog/datadog-api-client-ruby#301]
**Describe the bug**

I was unable to configure the client using the same interface the [documentation suggests](https://github.com/DataDog/datadog-api-client-ruby#authentication)

```
`block in configure': undefined method `application_key=' for #<DatadogAPIClient::V1::Configuration:0x00007ff3ec0f28e0> (NoMethodError)
```

**To Reproduce**

run the following script - This assumes the dependencies and OS outlined below

```ruby
    DatadogAPIClient::V1.configure do |config|
      config.api_key         = "the-api-key"
      config.application_key = "the-application-key"
    end
```

**Expected behavior**

The library gets configured and can be used

**Environment and Versions (please complete the following information):**

- `Mac OS  Catalina 10.15.7`
- `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]`
- `datadog_api_client (1.0.0.beta.2)`

**Comment by therve** [comment]
Hello,

Sorry for not checking this earlier. There was a small window where the documentation was more recent than the release, the doc applied to beta-3. Upgrading to the latest version should work, let us know if it doesn't. Thanks.
