### ISSUE TITLE
Dependencies segfault on aws arm64 ec2 classes, tracking for visibility

### ISSUE THREAD

**Issue by rromanchuk** [DataDog/datadog-api-client-ruby#709]
On require, segfault is thrown in dependencies. These are being tracked listed below, but titles may be misleading.  It's not just developers' M1 machines, but other production arm environments as well. 

https://github.com/ffi/ffi/issues/864
https://github.com/typhoeus/typhoeus/issues/667

**To Reproduce**
```
$ gem install datadog_api_client
$ irb
irb(main):001:0> require 'datadog_api_client/v2'

/home/ubuntu/shared_bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:275: [BUG] Segmentation fault at 0x0000ffff00000020
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [aarch64-linux]

-- Control frame information -----------------------------------------------
c:0048 p:---- s:0277 e:000276 CFUNC  :attach
c:0047 p:0247 s:0271 e:000270 METHOD /home/ubuntu/shared_bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:275
c:0046 p:0043 s:0251 e:000250 CLASS  /home/ubuntu/shared_bundle/ruby/3.1.0/gems/ethon-0.15.0/lib/ethon/libc.rb:17
c:0045 p:0007 s:0248 e:000247 CLASS  /home/ubuntu/shared_bundle/ruby/3.1.0/gems/ethon-0.15.0/lib/ethon/libc.rb:7
[clipped...]
```

**Environment and Versions (please complete the following information):**
- ruby 3.1.0 via rbenv
- Latest ubuntu LTS,  A1, T4g instances

**Additional context**
I can make a minimal reproducible AMI if it helps

**Comment by therve** [comment]
It should be fixed by #803 . Thanks!
