### ISSUE TITLE
Invalid LogsApi#list_logs example

### ISSUE THREAD

**Issue by Melchizedech** [DataDog/datadog-api-client-ruby#785]
**Describe the bug**
I'm trying to query logs using the logs_api & logs_list_request model from your repository.

When using the sample code in https://github.com/DataDog/datadog-api-client-ruby/blob/v1.7.0/examples/v2/logs/ListLogs.rb, it is raising an error.
```
/some/path/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/datadog_api_client-1.7.0/lib/datadog_api_client/v2/api/logs_api.rb:133:in `list_logs_with_http_info': undefined method `[]' for #<DatadogAPIClient::V2::LogsListRequest:0x000055d3a7a87c00 @filter=#<DatadogAPIClient::V2::LogsQueryFilter:0x000055d3a7a87f20 @from="2020-09-17T11:48:36+01:00", @indexes=["main"], @query="datadog-agent", @to="2020-09-17T12:48:36+01:00">, @page=#<DatadogAPIClient::V2::LogsListRequestPage:0x000055d3a7a87cf0 @limit=5>, @sort="timestamp"> (NoMethodError)  
```

It looks like your library is broken or the example is wrong.

**To Reproduce**

1. Execute the code from https://github.com/DataDog/datadog-api-client-ruby/blob/v1.7.0/examples/v2/logs/ListLogs.rb
2. It isn't working

**Expected behavior**
I can request logs using the list logs API.

**Environment and Versions (please complete the following information):**
ruby 3.0.2 with datadog_api_client 1.7.0
Linux  5.16.12-arch1-1 #1 SMP PREEMPT Wed, 02 Mar 2022 12:22:51 +0000 x86_64 GNU/Linux

**Comment by therve** [comment]
Hi,

This is a generated example that's wrong indeed. It needs to read:

```ruby
p api_instance.list_logs({body: body})
```

We'll look into fixing it, thanks.
