### ISSUE TITLE
datadog_api_client Timeout error submitting metrics

### ISSUE THREAD

**Issue by adrys-lab** [DataDog/datadog-api-client-ruby#934]
**Describe the bug**
We are facing timeout issues trying to submit metrics into the Datadog API by using the `datadog_api_client` gem.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/35842560/172314104-e3ba7bb6-cb6e-4f0a-b561-89413657c3cd.png">

**Client initializer:**
```
DatadogAPIClient::V1.configure do |config|
  config.api_key = ENV['DATADOG_API_KEY']
end
```

**Metric sender**
```
def self.push_metric(metric_event:, metric_type:, metric_value:, tags:)
    metric = DatadogAPIClient::V1::MetricsPayload.new(
      {
        series: [
          DatadogAPIClient::V1::Series.new(
            {
              metric: metric_event,
              type: metric_type,
              points: [
                [
                  Time.zone.now.to_f,
                  metric_value,
                ],
              ],
              tags: tags,
            }
          ),
        ],
      }
    )
    DatadogClient.metrics_api_client.submit_metrics(metric)
  rescue StandardError => error
    WebLogger.warning(
      event: 'datadog_push_metric_error',
      message: 'Error on push metrics to Datadog',
      args: { metric_event: metric_event, metric_type: metric_type, tags: tags },
      error: error
    )
  end

  def self.metrics_api_client
    @metrics_api_client ||= DatadogAPIClient::V1::MetricsAPI.new
  end
```

**Gem version**
`datadog_api_client (1.8.0)`

The issue does not happen always, it seems randomly to our eyes.

**Comment by therve** [comment]
Thanks for your report.
 Do you have any hints on what might happen? Do you always use the same set of tags? 
It's possible it's just a transient/network error. 504 is safe to retry, I think that would be the right approach here.

**Comment by adrys-lab** [comment]
yes we usually use the same TAGS, not real-time based.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/35842560/172316637-8f53b53b-45a7-47db-9b8c-833a1dcf77a2.png">

of course i understand we can retry the operation, but i wanted to know the reason on why the API is giving us randome **Timeout** for the same operations.
